name: Selenium Tests

on:
  push:
    branches:
      - main

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build and run .NET app
        run: docker-compose -f docker-compose.yml up -d --build

      - name: Run Selenium tests
        run: docker-compose -f docker-compose.yml run mywebapp-tests

      - name: Stop Selenium Grid and .NET app
        run: docker-compose -f docker-compose.yml down
