version: '3'

services:
  selenium-hub:
    image: selenium/hub:4.11.0-20231106  # Specify the exact version
    container_name: selenium-hub # Add container name for the hub
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:4.11.0-20231106 # Specify the exact version
    container_name: chrome # Add container name for Chrome node
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  mywebapp:
    build: ./MyWebApp
    container_name: mywebapp  # Add container name for the web app

  mywebapp-tests:
    build: ./MyWebApp.Tests
    container_name: mywebapp-tests  # Add container name for the tests
    depends_on:
      - selenium-hub
      - mywebapp
