name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0'  # Adjust the .NET version as per your project requirement

      - name: Create custom Docker network
        run: |
          docker network create selenium-grid

      - name: Build .NET application
        run: dotnet build --configuration Release

      - name: Build Docker image for .NET application
        run: |
          docker build -t sample-dotnet-app -f SampleDotNetApp/Dockerfile .

      - name: Run Selenium Hub
        run: |
          docker run -d --name selenium-hub --network selenium-grid -p 4444:4444 selenium/hub:4.21.0-20240522

      - name: Run Selenium Chrome Node
        run: |
          docker run -d --name selenium-chrome --network selenium-grid --shm-size=2g -e SE_EVENT_BUS_HOST=selenium-hub -e SE_EVENT_BUS_PUBLISH_PORT=4442 -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 selenium/node-chrome:4.21.0-20240522

      - name: Run Selenium Edge Node
        run: |
          docker run -d --name selenium-edge --network selenium-grid --shm-size=2g -e SE_EVENT_BUS_HOST=selenium-hub -e SE_EVENT_BUS_PUBLISH_PORT=4442 -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 selenium/node-edge:4.21.0-20240522

      - name: Run Selenium Firefox Node
        run: |
          docker run -d --name selenium-firefox --network selenium-grid --shm-size=2g -e SE_EVENT_BUS_HOST=selenium-hub -e SE_EVENT_BUS_PUBLISH_PORT=4442 -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 selenium/node-firefox:4.21.0-20240522

      - name: Run Docker container for .NET application
        run: |
          docker run -d --name sample-dotnet-app --network selenium-grid -p 8080:80 sample-dotnet-app

      - name: Wait for .NET application to be ready
        run: |
          sleep 30 # Adjust this duration based on your app's startup time

      - name: Wait for Selenium Grid to be ready
        run: |
          sleep 180 # Increased wait time to ensure Selenium Grid is up

      - name: Check Selenium Grid status
        run: |
          curl http://localhost:4444/wd/hub/status

      - name: Check running Docker containers
        run: |
          docker ps -a

      - name: Check network connections
        run: |
          docker network ls
          docker network inspect selenium-grid

      - name: Inspect Chrome Node Logs
        run: |
          docker logs selenium-chrome

      - name: Inspect Edge Node Logs
        run: |
          docker logs selenium-edge

      - name: Inspect Firefox Node Logs
        run: |
          docker logs selenium-firefox

      - name: Restore dependencies for tests
        run: dotnet restore SampleDotNetApp.Tests

      - name: Run tests
        env:
          HUB_HOST: selenium-hub
        run: dotnet test SampleDotNetApp.Tests --logger:"trx;LogFileName=TestResults.trx"

      - name: Publish Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: TestResults
          path: TestResults.trx

      - name: Clean up Docker containers
        run: |
          docker stop selenium-hub selenium-chrome selenium-edge selenium-firefox sample-dotnet-app
          docker rm selenium-hub selenium-chrome selenium-edge selenium-firefox sample-dotnet-app
          docker network rm selenium-grid
