name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      selenium-hub:
        image: selenium/hub:4.21.0-20240522
        ports:
          - 4444:4444
      selenium-chrome:
        image: selenium/node-chrome:4.21.0-20240522
        options: --shm-size=2g
      selenium-edge:
        image: selenium/node-edge:4.21.0-20240522
        options: --shm-size=2g
      selenium-firefox:
        image: selenium/node-firefox:4.21.0-20240522
        options: --shm-size=2g

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0'  # Adjust the .NET version as per your project requirement

      - name: Build .NET application
        run: dotnet build --configuration Release

      - name: Build Docker image for .NET application
        run: |
          docker build -t sample-dotnet-app -f SampleDotNetApp/Dockerfile .

      - name: Run Docker container for .NET application
        run: |
          docker run -d -p 8080:80 --name sample-dotnet-app sample-dotnet-app

      - name: Wait for .NET application to be ready
        run: |
          sleep 30 # Adjust this duration based on your app's startup time

      - name: Wait for Selenium Grid to be ready
        run: |
          sleep 120 # Increased wait time to ensure Selenium Grid is up

      - name: Check Selenium Grid status
        run: |
          curl http://localhost:4444/wd/hub/status

      - name: Check running Docker containers
        run: |
          docker ps -a

      - name: Check network connections
        run: |
          docker network ls
          docker network inspect github_network

      - name: Restore dependencies for tests
        run: dotnet restore SampleDotNetApp.Tests

      - name: Run tests
        env:
          HUB_HOST: selenium-hub
        run: dotnet test SampleDotNetApp.Tests --logger:"trx;LogFileName=TestResults.trx"

      - name: Publish Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: TestResults
          path: TestResults.trx

      - name: Clean up Docker containers
        run: |
          docker stop sample-dotnet-app
          docker rm sample-dotnet-app
