name: .NET

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Start Selenium Hub
      run: docker run -d --name selenium-hub --network selenium-grid -p 4444:4444 selenium/hub:4.21.0-20240522

    - name: Start Chrome Node
      run: docker run -d --name selenium-chrome --network selenium-grid -e SE_EVENT_BUS_HOST=selenium-hub selenium/node-chrome:4.21.0-20240522

    - name: Wait for Selenium Grid to be ready
      run: |
        until curl -s http://localhost:4444/wd/hub/status | grep -q '"ready": true'; do
          sleep 1
        done

    - name: Run .NET tests
      run: dotnet test SampleDotNetApp.Tests --logger:"trx;LogFileName=TestResults.trx" -v d

    - name: Upload test logs
      uses: actions/upload-artifact@v2
      with:
        name: test-log
        path: SampleDotNetApp.Tests/TestResults/test-log.txt
