name: Selenium Tests

on:
  push:
    branches:
      - main  # Adjust if you use a different branch name

jobs:
  selenium-tests:
    runs-on: ubuntu-latest # Or your preferred runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # Or the exact version you're using

      - name: Install Docker Compose
        run: |
          DOCKER_CONFIG=${HOME}/.docker
          mkdir -p ${DOCKER_CONFIG}
          curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose

      - name: Build and run services
        run: docker-compose up -d --build

      - name: Run Selenium tests
        run: docker-compose run mywebapp-tests

      - name: Stop Selenium Grid and .NET app
        run: docker-compose down


# name: Selenium Tests

# on:
#   push:
#     branches:
#       - "**"

# jobs:
#   selenium-tests:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Start Selenium Grid
#         run: docker-compose up -d

#       - name: Build and run .NET app
#         run: docker-compose up -d mywebapp  # Use the container name

#       - name: Run Selenium tests
#         run: docker-compose run mywebapp-tests  # Use the container name

#       - name: Stop Selenium Grid and .NET app
#         run: docker-compose down
