name: Selenium Tests with Results Report

on:
  push:
    branches:
      - main

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Install Docker Compose V2
        uses: docker/setup-buildx-action@v2

      - name: Build and run services
        run: docker compose up -d --build

      - name: Run Selenium tests
        run: docker compose run --rm -T mywebapp-tests
      
      - name: Copy test results
        run: docker cp sampledotnetapp_mywebapp-tests_run:/app/MyWebApp.Tests/TestResults ./TestResults

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: TestResults/**/*.trx
          
      - name: Stop Selenium Grid and .NET app
        run: docker compose down
