name: Windows PowerShell Service Workflow

on: [push]

jobs:
  run-service:
    runs-on: sample
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy service script to runner
        run: |
          New-Item -Path "C:\MyService" -ItemType Directory -Force
          Copy-Item -Path ./MyService.ps1 -Destination C:\MyService\MyService.ps1

      - name: Run PowerShell service registration
        shell: powershell
        run: |
          ./Register-Service.ps1


# name: SCP Deploy

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: winsrv19
#     permissions: write-all
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Verify OpenSSH Installation
#         run: |
#           Get-Command scp
#         #   ssh -V
#         shell: powershell

#       - name: Run SCP Transfer Script
#         run: |
#           $scpPath = "C:\Windows\System32\OpenSSH\scp.exe"
#           $sourcePath = "c:\Runners\GitHub\actions-runner\_work\SampleDotNetApp\SampleDotNetApp\MyWebApp\obj\*.json"
#           $destPath = "admin@192.168.0.57:C:\Users\admin\"
#           .\transfer.ps1 -scpPath $scpPath -sourcePath $sourcePath -destPath $destPath
#         shell: powershell



# name: SCP Deploy

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: winsrv19
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Verify OpenSSH Installation
#         run: |
#           Get-Command scp
#         #   ssh -V
#         shell: powershell

#       - name: Debug Paths
#         run: |
#           $scpPath = "C:\Windows\System32\OpenSSH\scp.exe"
#           $sourcePath = "c:\Runners\GitHub\actions-runner\_work\SampleDotNetApp\SampleDotNetApp\MyWebApp\obj\*.json"
#           $destPath = "admin@192.168.0.57:C:\Users\admin\"
#           Write-Output "SCP Path: $scpPath"
#           Write-Output "Source Path: $sourcePath"
#           Write-Output "Destination Path: $destPath"
#         shell: powershell

#       - name: Copy files using SCP with Verbose Output
#         run: |
#           $scpPath = "C:\Windows\System32\OpenSSH\scp.exe"
#           $sourcePath = "c:\Runners\GitHub\actions-runner\_work\SampleDotNetApp\SampleDotNetApp\MyWebApp\obj\*.json"
#           $destPath = "admin@192.168.0.57:C:\Users\admin\"
#           & $scpPath -vvv -i "$env:USERPROFILE\.ssh\id_ed25519" $sourcePath $destPath
#         shell: powershell


# name: SCP Deploy

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: winsrv19
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Verify OpenSSH Installation
#         run: |
#           Get-Command scp
#           Get-Command ssh
#         shell: powershell

#       - name: Debug Paths
#         run: |
#           $scpPath = "C:\Windows\System32\OpenSSH\scp.exe"
#           $sshPath = "C:\Windows\System32\OpenSSH\ssh.exe"
#           $sourcePath = ".\MyWebApp\obj\MyWebApp.csproj.nuget.dgspec.json"
#           $destPath = "admin@192.168.0.57:C:\Users\admin\"
#           Write-Output "SCP Path: $scpPath"
#           Write-Output "SSH Path: $sshPath"
#           Write-Output "Source Path: $sourcePath"
#           Write-Output "Destination Path: $destPath"
#         shell: powershell

#       - name: Copy files using SCP
#         run: |
#           $scpPath = "C:\Windows\System32\OpenSSH\scp.exe"
#           $sourcePath = ".\MyWebApp\obj\MyWebApp.csproj.nuget.dgspec.json"
#           $destPath = "admin@192.168.0.57:C:\Users\admin\"
#           Start-Process -FilePath $scpPath -ArgumentList @('-i', "$env:USERPROFILE\.ssh\id_ed25519", $sourcePath, $destPath) -Wait
#         shell: powershell

#       - name: Verify file on remote server
#         run: |
#           $sshPath = "C:\Windows\System32\OpenSSH\ssh.exe"
#           & $sshPath -i "$env:USERPROFILE\.ssh\id_ed25519" admin@192.168.0.57 "dir C:\Users\admin"
#         shell: powershell


# name: SCP Deploy

# on:
#   push:
#     branches:
#       - "**"

# jobs:
#   deploy:
#     runs-on: winsrv19
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Verify OpenSSH Installation
#         run: |
#           Get-Command scp
#         shell: powershell

#       - name: Debug Paths
#         run: |
#           $scpPath = "C:\Windows\System32\OpenSSH\scp.exe"
#           $sourcePath = ".\MyWebApp\obj\MyWebApp.csproj.nuget.dgspec.json"
#           $destPath = "admin@192.168.0.57:C:\Users\admin\"
#           Write-Output "SCP Path: $scpPath"
#           Write-Output "Source Path: $sourcePath"
#           Write-Output "Destination Path: $destPath"
#         shell: powershell

#       - name: Copy files using SCP
#         run: |
#           $scpPath = "C:\Windows\System32\OpenSSH\scp.exe"
#           $sourcePath = ".\MyWebApp\obj\MyWebApp.csproj.nuget.dgspec.json"
#           $destPath = "admin@192.168.0.57:C:\Users\admin\"
#           Start-Process -FilePath $scpPath -ArgumentList @('-i', "$env:USERPROFILE\.ssh\id_ed25519", $sourcePath, $destPath) -Wait
#         shell: powershell

#       - name: Verify file on remote server
#         run: |
#           ssh -i "$env:USERPROFILE\.ssh\id_ed25519" admin@192.168.0.57 "dir C:\Users\admin"
#         shell: powershell