name: SCP Deploy

on:
  push:
    branches:
      - "**"

jobs:
  deploy:
    runs-on: winsrv19
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Verify OpenSSH Installation
        run: |
          Get-Command scp
        shell: powershell

      - name: Copy files using SCP
        run: |
          $scpPath = "C:\Windows\System32\OpenSSH\scp.exe"
          $sourcePath = ".\MyWebApp\obj\MyWebApp.csproj.nuget.dgspec.json"
          $destPath = "admin@192.168.0.57:C:\Users\admin\"
          Start-Process -FilePath $scpPath -ArgumentList @('-i', "$env:USERPROFILE\.ssh\id_ed25519", $sourcePath, $destPath) -Wait
        shell: powershell

      # - name: Copy files using SCP
      #   run: |
      #     $scpPath = "C:\Windows\System32\OpenSSH\scp.exe"
      #     $sourcePath = ".\MyWebApp\obj\MyWebApp.csproj.nuget.dgspec.json"
      #     $destPath = "admin@192.168.0.57:C:\Users\admin\"
      #     & $scpPath -i "$env:USERPROFILE\.ssh\id_ed25519" $sourcePath $destPath
      #   shell: powershell

      # # - name: Copy files using SCP
      #   run: |
      #     scp.exe -i "%USERPROFILE%\.ssh\id_ed25519" ".\MyWebApp\obj\MyWebApp.csproj.nuget.dgspec.json" admin@192.168.0.57:C:\Users\admin\
      #   # shell: cmd /c
        # env:
        #   PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

# name: Selenium Tests with Results Report

# on:
#   push:
#     branches:
#       - main

# jobs:
#   selenium-tests:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v3
#       - name: Set up .NET
#         uses: actions/setup-dotnet@v3
#         with:
#           dotnet-version: '8.0.x'

#       - name: Install Docker Compose V2
#         run: |
#            sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
#            sudo chmod +x /usr/local/bin/docker-compose

#       - name: Build and run services
#         run: docker compose up -d --build

#       - name: Run Selenium tests
#         run: docker compose run --rm -T mywebapp-tests

#       - name: Copy test results
#         run: docker cp sampledotnetapp_mywebapp-tests_run:/app/MyWebApp.Tests/TestResults ./TestResults

#       - name: Publish Test Results
#         uses: EnricoMi/publish-unit-test-result-action@v2
#         continue-on-error: true
#         if: always()
#         with:
#           files: TestResults/**/*.trx

#       - name: Stop Selenium Grid and .NET app
#         run: docker compose down

